name: traffic_control_dashboard
description: A Flutter dashboard for monitoring traffic control agents.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  google_maps_flutter_platform_interface: ^2.4.0
  flutter_dotenv: ^5.1.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
